1. Load the "ModifiedEdibleMushroom.csv" data from the link below (note: this data set has been preliminarily prepared.) again.

https://github.com/kaopanboonyuen/Python-Data-Science/raw/master/Dataset/hed2020_dataset.csv

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('https://github.com/kaopanboonyuen/Python-Data-Science/raw/master/Dataset/hed2020_dataset.csv')
df

id label cap-shape cap-surface bruises odor gill-attachment  \
0        1     p         x           s       t    p               f   
1        2     e         x           s       t    a               f   
2        3     e         b           s       t    l               f   
3        4     p         x           y       t    p               f   
4        5     e         x           s       f    n               f   
...    ...   ...       ...         ...     ...  ...             ...   
5819  5820     e         k           s       f    n               a   
5820  5821     e         x           s       f    n               a   
5821  5822     e         f           s       f    n               a   
5822  5823     p         k           y       f    y               f   
5823  5824     e         x           s       f    n               a   

     gill-spacing gill-size stalk-shape  ... ring-number ring-type  \
0               c         n           e  ...           o         p   
1               c         b           e  ...           o         p   
2               c         b           e  ...           o         p   
3               c         n           e  ...           o         p   
4               w         b           t  ...           o         e   
...           ...       ...         ...  ...         ...       ...   
5819            c         b           e  ...           o         p   
5820            c         b           e  ...           o         p   
5821            c         b           e  ...           o         p   
5822            c         n           t  ...           o         e   
5823            c         b           e  ...           o         p   

     spore-print-color population habitat cap-color-rate gill-color-rate  \
0                    k          s       u            1.0             3.0   
1                    n          n       g            2.0             3.0   
2                    n          n       m            3.0             1.0   
3                    k          s       u            3.0             1.0   
4                    n          a       g            4.0             3.0   
...                ...        ...     ...            ...             ...   
5819                 b          c       l            1.0            10.0   
5820                 b          v       l            1.0            10.0   
5821                 b          c       l            1.0             1.0   
5822                 w          v       l            1.0             9.0   
5823                 o          c       l            1.0            10.0   

     veil-color-rate stalk-color-above-ring-rate  stalk-color-below-ring-rate  
0                1.0                         1.0                          1.0  
1                1.0                         1.0                          1.0  
2                1.0                         1.0                          1.0  
3                1.0                         1.0                          1.0  
4                1.0                         1.0                          1.0  
...              ...                         ...                          ...  
5819             2.0                         7.0                          8.0  
5820             1.0                         7.0                          8.0  
5821             2.0                         7.0                          8.0  
5822             1.0                         1.0                          1.0  
5823             2.0                         7.0                          8.0  

[5824 rows x 24 columns]

2. Choose edible mushrooms only.

In [2]:
df2=df[df.label=='e']
df2

id label cap-shape cap-surface bruises odor gill-attachment  \
1        2     e         x           s       t    a               f   
2        3     e         b           s       t    l               f   
4        5     e         x           s       f    n               f   
5        6     e         x           y       t    a               f   
6        7     e         b           s       t    a               f   
...    ...   ...       ...         ...     ...  ...             ...   
5815  5816     e         x           s       f    n               a   
5819  5820     e         k           s       f    n               a   
5820  5821     e         x           s       f    n               a   
5821  5822     e         f           s       f    n               a   
5823  5824     e         x           s       f    n               a   

     gill-spacing gill-size stalk-shape  ... ring-number ring-type  \
1               c         b           e  ...           o         p   
2               c         b           e  ...           o         p   
4               w         b           t  ...           o         e   
5               c         b           e  ...           o         p   
6               c         b           e  ...           o         p   
...           ...       ...         ...  ...         ...       ...   
5815            c         b           e  ...           o         p   
5819            c         b           e  ...           o         p   
5820            c         b           e  ...           o         p   
5821            c         b           e  ...           o         p   
5823            c         b           e  ...           o         p   

     spore-print-color population habitat cap-color-rate gill-color-rate  \
1                    n          n       g            2.0             3.0   
2                    n          n       m            3.0             1.0   
4                    n          a       g            4.0             3.0   
5                    k          n       g            2.0             1.0   
6                    k          n       m            3.0             2.0   
...                ...        ...     ...            ...             ...   
5815                 o          v       l            1.0            10.0   
5819                 b          c       l            1.0            10.0   
5820                 b          v       l            1.0            10.0   
5821                 b          c       l            1.0             1.0   
5823                 o          c       l            1.0            10.0   

     veil-color-rate stalk-color-above-ring-rate  stalk-color-below-ring-rate  
1                1.0                         1.0                          1.0  
2                1.0                         1.0                          1.0  
4                1.0                         1.0                          1.0  
5                1.0                         1.0                          1.0  
6                1.0                         1.0                          1.0  
...              ...                         ...                          ...  
5815             2.0                         7.0                          8.0  
5819             2.0                         7.0                          8.0  
5820             1.0                         7.0                          8.0  
5821             2.0                         7.0                          8.0  
5823             2.0                         7.0                          8.0  

[2104 rows x 24 columns]

3.  Only the variables below have been selected to describe the distinctive characteristics of edible mushrooms

'cap-color-rate','stalk-color-above-ring-rate'

In [3]:
df=df2[['cap-color-rate','stalk-color-above-ring-rate']]
df

cap-color-rate  stalk-color-above-ring-rate
1                2.0                          1.0
2                3.0                          1.0
4                4.0                          1.0
5                2.0                          1.0
6                3.0                          1.0
...              ...                          ...
5815             1.0                          7.0
5819             1.0                          7.0
5820             1.0                          7.0
5821             1.0                          7.0
5823             1.0                          7.0

[2104 rows x 2 columns]

4. Provide a proper data preprocessing as follows:

- Fill missing with mean 

- Standardize variables with Standard Scaler

In [4]:
#Fill mean
df.fillna(df.mean(),inplace=True)
df

/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py:6392: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


cap-color-rate  stalk-color-above-ring-rate
1                2.0                          1.0
2                3.0                          1.0
4                4.0                          1.0
5                2.0                          1.0
6                3.0                          1.0
...              ...                          ...
5815             1.0                          7.0
5819             1.0                          7.0
5820             1.0                          7.0
5821             1.0                          7.0
5823             1.0                          7.0

[2104 rows x 2 columns]

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(df)
df=scaler.transform(df)

In [6]:
df

array([[-0.73500484, -0.74760802],
       [-0.23417985, -0.74760802],
       [ 0.26664515, -0.74760802],
       ...,
       [-1.23582983,  2.43279003],
       [-1.23582983,  2.43279003],
       [-1.23582983,  2.43279003]])

5. K-means clustering with 5 clusters and seed = 2020.

In [7]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=5,random_state=2020).fit(df)
kmeans

KMeans(n_clusters=5, random_state=2020)

6. Show the centroid of each cluster.

In [8]:
kmeans.cluster_centers_

array([[ 0.41361805, -0.37536859],
       [-1.23582983,  2.30658376],
       [-1.22906193, -0.29354739],
       [ 2.5059661 , -0.74760802],
       [ 1.2093128 ,  1.90272369]])

7. Convert the centroid value to the original scale

In [9]:
scaler.inverse_transform(kmeans.cluster_centers_)

array([[4.2934616 , 1.70225065],
       [1.        , 6.76190476],
       [1.01351351, 1.85661095],
       [8.47126437, 1.        ],
       [5.88222965, 6.        ]])

group 0 กลุ่มที่ cap-color-rate มีค่ากลาง ๆ stalk-color-above-ring-rate มีค่าน้อย 

group 1 กลุ่มที่ cap-color-rate มีค่าน้อย แต่ stalk-color-above-ring-rate มีค่ามาก

group 2 กลุ่มที่ cap-color-rate และ stalk-color-above-ring-rate มีค่าน้อยทั้งคู่

group 3 กลุ่มที่ cap-color-rate มีค่ามาก stalk-color-above-ring-rate มีค่าน้อย

group 4 กลุ่มที่ cap-color-rate มีค่ากลาง ๆ  stalk-color-above-ring-rate มีค่ามาก